---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $.Chart.Name }}-crons
  namespace: {{ $.Values.namespace }}
spec:
  schedule: "@hourly"
  jobTemplate:
    spec:
      suspend: true
      template:
        spec:
          nodeSelector:
            "node.kubernetes.io/instance-type": {{ quote (coalesce .node_selector $.Values.node_selector) }}
          containers:
          {{- range $.Values.crons }}
            - name: {{ lower .name }}
              image: {{ $.Values.image.repo }}:{{ coalesce .release $.Values.image.release }}
              command: ['sh', '-c', 'npm run crons']
              env:
                - name: RUN_CRON_NAME
                  value: {{ .name }}
              {{- range $k, $v := $.Values.adapter_env }}
                - name: {{ $k }}
                  value: {{ quote $v }}
              {{- end }}
              {{- range .env }}
                - name: {{ .name }}
                  value: {{ quote .value }}
              {{- end }}
              envFrom:
                - configMapRef:
                    name: {{ $.Chart.Name }}-env
                - secretRef:
                    name: {{ $.Chart.Name }}-secrets
          {{- end}}
          restartPolicy: Never