apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Chart.Name }}-secrets
  namespace: {{ $.Values.namespace }}
type: Opaque
data:
{{- range $k, $v := $.Values.secrets }}
  {{ $k }}: {{ b64enc $v }}
{{- end}}