{{- range $task := $.Values.tasks }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $.Chart.Name }}-task-{{ lower .name }}
  namespace: {{ $.Values.namespace }}
spec:
  parallelism: 1
  suspend: {{ $task.suspend }}
  template:
    spec:
      nodeSelector:
        "node.kubernetes.io/instance-type": {{ quote (coalesce .node_selector $.Values.node_selector) }}
      containers:
      {{- range $task.containers }}
        - name: {{ lower .name }}
          image: {{ $.Values.image.repo }}:{{ coalesce $task.release $.Values.cron_defaults.image.release $.Values.image.release }}
          command: ['sh', '-c', 'npm run crons']
          env:
            - name: RUN_CRON_NAME
              value: {{ $task.cronName }}
          {{- range $k, $v := (mergeOverwrite (dict) $.Values.adapter_env $.Values.cron_defaults.env (coalesce .env (dict))) }}
            - name: {{ $k }}
              value: {{ quote $v }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ $.Chart.Name }}-env
            - secretRef:
                name: {{ $.Chart.Name }}-secrets
      {{- end }}
      restartPolicy: Never
{{- end}}